basic_metrics:
  oa:
    api: &api
      # API configuration
      mails:
        - "marion.restrepo@innpulsacolombia.com"
        - "alejandro.garcia@innpulsacolombia.com"
        - "juan.pablo.garcia@upf.edu"
        - "emilio.fernandez@upf.edu"
        - "jeremy.davis@nesta.org.uk"
        - "sara.garcia-arteagoitia@nesta.org.uk"
        - "maria.sorbo@ec.europa.eu"
      perpage: "200"
    filter: author.id
    n_jobs: 8
    batch_size: 1000
    publications_endpoint: works
    keys_to_include:
      - "id"
      - "publication_date"
      - "fwci"
      - "cited_by_count"
      - "authorships"
      - "topics"
      - "referenced_works"

complex_metrics:
  oa:
    api: *api
    select_variables:
      - "id"
      - "referenced_works"
    keys_to_include:
      - "id"
      - "referenced_works"
    filter: cites
    n_jobs: 8
    batch_size: 1000
    publications_endpoint: works