basic_metrics:
  oa:
    api: &api
      # API configuration
      mails:
        - "david.ampudia@nesta.org.uk"
        - "data_analytics@nesta.org.uk"
        - "david.ampudia@bse.eu"
        - "david.ampudia@upf.edu"
        - "george.richardson@nesta.org.uk"
        - "yanyan.leung@nesta.org.uk"
        - "innovationgrowthlab@nesta.org.uk"
      mailto: "innovationgrowthlab@nesta.org.uk"
      perpage: "200"
    filter: author.id
    n_jobs: 8
    batch_size: 1000
    publications_endpoint: works
    keys_to_include:
      - "id"
      - "publication_date"
      - "fwci"
      - "authorships"
      - "topics"
      - "referenced_works"

complex_metrics:
  oa:
    api: *api
    select_variables:
      - focal:
          - "id"
          - "referenced_works"
      - reference:
          - "id"
          - "citation_percentile"
          - "referenced_works"
    filter: cites
    n_jobs: 8
    batch_size: 1000
    publications_endpoint: works