model_training:
  test_size: 0.1
  random_seed: 42

  base_params:
    n_estimators: [1000, 1300]
    max_depth: [11, 15, 19]
    learning_rate: [0.1]
    min_child_weight: [1]
    gamma: [0]
    subsample: [0.8, 1.0]
    max_delta_step: [5, 10]    # Can help with class imbalance
    reg_alpha: [0.0, 0.2]     # L1 regularization
    reg_lambda: [0.0, 0.2]    # L2 regularization

  # SMOTE specific parameters
  smote:
    enabled: true
    k_neighbors: [9, 13]

  cv:
    n_splits: 5
    shuffle: true

  # Grid search
  grid_search:
    scoring: "f1"
    n_jobs: 8
    verbose: 10

model_prediction:
  model_choice: "class_weights_model"
  threshold: 0.8
